### ISSUE TITLE
Do we really need BULMA css ?

### ISSUE THREAD

**Issue by adsingh14** [NiallEccles/Hacktoberfest-animations#125]
This small project is using BULMA css, but still you're not using it in standardized way. I think we don't need BULMA css for just a single **select** input. 

I will help you to create the same output using custom CSS only. In that way, this project could load faster by not fetching CDN file.

**Comment by NiallEccles** [comment]
We may not need bulma.css. If you can replicate the same styling currently without bulma then I am more than happy to forgo it.

**Comment by adsingh14** [comment]
Here it is, https://github.com/NiallEccles/Hacktoberfest-animations/pull/145.

**Comment by adsingh14** [comment]
@NiallEccles https://github.com/NiallEccles/Hacktoberfest-animations/pull/171

**Comment by adsingh14** [comment]
@NiallEccles https://github.com/NiallEccles/Hacktoberfest-animations/pull/171 Please check that PR.
