### ISSUE TITLE
Fix broken animations

### ISSUE THREAD

**Issue by NiallEccles** [NiallEccles/Hacktoberfest-animations#132]
A number of animations do nothing at all. They might be missing a class name within the file, an improperly formatted selector in animations.js or some other issue.

We would need to go through each animation, find those which are not working, and fix them. This may also involve referencing the original pull request for that animation and see what has changed since then or fix the issue that was originally present.

**Comment by fernandadagostin** [comment]
hi, I am working on this.
Can you sign this issue to my name?

**Comment by NiallEccles** [comment]
> hi, I am working on this.
> Can you sign this issue to my name?

Done!

**Comment by adsingh14** [comment]
I will do it !

**Comment by fernandadagostin** [comment]
I fixed all the problems I found and added my own animation (ghost). PR #141
