### ISSUE TITLE
Animation doesn't play when page first loads

### ISSUE THREAD

**Issue by NiallEccles** [NiallEccles/Hacktoberfest-animations#3]
When the page first loads the first animation does not play. This is because we only run the animation once the select field changes value. Perhaps this should first animate when the page loads.

**Comment by justiceotuya** [comment]
can i work on this?

**Comment by NiallEccles** [comment]
@justiceotuya Absolutely!

**Comment by justiceotuya** [comment]
i need access

**Comment by NiallEccles** [comment]
Hey @justiceotuya I've merged your pull request. Thanks for your help!
