### ISSUE TITLE
User 'reebr' not found

### ISSUE THREAD

**Issue by BaseMax** [NiallEccles/Hacktoberfest-animations#376]
Hi,

User 'reebr' not found.
https://github.com/reebr

We can see this broken link at: https://github.com/NiallEccles/Hacktoberfest-animations#notable-contributions

Regards,
Max

**Comment by NiallEccles** [comment]
Thanks for spotting this! It looks like they changed their name. I think it is [https://github.com/rn4n](rn4n) based on the commits they made to this repo.

**Comment by NiallEccles** [comment]
I have updated the readme with the new link.
