### ISSUE TITLE
shake animation

### ISSUE THREAD

**Issue by adrsh79086** [NiallEccles/Hacktoberfest-animations#387]
In animation there is an animation of name shake is not working .
![Screenshot (47)](https://user-images.githubusercontent.com/72243915/97879363-e7923600-1d45-11eb-99fc-70a9146731bc.png)

AND i want to submit my code which is working.

**Comment by yadavashishdhirendra** [comment]
@adrsh79086 Yeah True shake animation is not working! Hey @NiallEccles can u assign it to me so I can fix that issue!

**Comment by NiallEccles** [comment]
> @adrsh79086 Yeah True shake animation is not working! Hey @NiallEccles can u assign it to me so I can fix that issue!

Are you sure it's still not working? This seems to be an old issue. It appears to be working now - at least it is for me.

**Comment by darshikaguptaa** [comment]
Hey,
I'd like to work on this issue. Can you please assign it to me?
