### ISSUE TITLE
Hacktoberfest Halloween Colors Changer

### ISSUE THREAD

**Issue by ainneo** [NiallEccles/Hacktoberfest-animations#393]
Hello @NiallEccles 
I created my first CSS animation PR for Hacktoberfest 2021! 
PR #392
Animation name: ainneone
Description: It changes colors from orange, purple, and red on a black background to convey Halloween!
I would love to have it accepted and labeled for Hacktoberfest and merged to main.
Thanks!

![Screen Shot 2021-10-04 at 8 54 36 PM](https://user-images.githubusercontent.com/38201574/135957577-91a59fef-1245-4323-b3e4-86252bfdc9bf.png)
![Screen Shot 2021-10-04 at 8 54 17 PM](https://user-images.githubusercontent.com/38201574/135957581-ef713cf0-8d92-4fc5-86f6-511f1a34cf4c.png)

**Comment by vivekarora-02** [comment]
Hey there,
I would like to contribute towards this issue. Can ypu please assign me this issue?

ThankYou!

**Comment by ainneo** [comment]
Hi @NiallEccles, just checking in. Is there an issue with my animation/PR? can we still make submissions for hacktoberfest? Please let me know, and I will fix my issues. Many thanks for putting together this awesome project!

**Comment by NiallEccles** [comment]
> Hey there, I would like to contribute towards this issue. Can ypu please assign me this issue?
> 
> ThankYou!

You can just make a pull request and I'll review it!

**Comment by NiallEccles** [comment]
PR was merged :)

https://github.com/NiallEccles/Hacktoberfest-animations/pull/392
