### ISSUE TITLE
add zoom animation

### ISSUE THREAD

**Issue by vishalnakumdev** [NiallEccles/Hacktoberfest-animations#396]
Hello @NiallEccles
I created my first CSS animation PR for Hacktoberfest 2021!
PR #395
Animation name: zoom
Thanks!

**Comment by ashutosh5003** [comment]
Hey please assign this issue to me.

**Comment by SohanaShabnam05** [comment]
Hey , please assign me for this issue

**Comment by Akash-1gif** [comment]
Hey, I'm interested to work on this issue. Please assign it to me

**Comment by Shreyaww** [comment]
Hey, Please assign this to me.
