### ISSUE TITLE
Must it be done with css

### ISSUE THREAD

**Issue by codeknight1** [NiallEccles/Hacktoberfest-animations#469]
Can i use Tailwind for the animation.

**Comment by NiallEccles** [comment]
Hey 👋 Yes it must be done with CSS. However, you could copy the compiled Tailwind animation and use that as your animation.

**Comment by codeknight1** [comment]
Alright... thanks

**Comment by ashutosh5003** [comment]
This issue hasn't been assigned to anyone so  can you assign this issue to me?

**Comment by 123shuklaayush** [comment]
hi sir, can you please assign this task to me
I can add some 3d effects using css

**Comment by SohanaShabnam05** [comment]
can I fix this issue please?

**Comment by 123shuklaayush** [comment]
Sir, I've created a 3d CSS text. Please assign it to me so that I could send you PR

**Comment by SohanaShabnam05** [comment]
Thanks for assigning me.

**Comment by NiallEccles** [comment]
Closing as this has been addressed.
