### ISSUE TITLE
Button with hover and blur animation

### ISSUE THREAD

**Issue by sidhrth04** [NiallEccles/Hacktoberfest-animations#526]

**Comment by sneha-mariam** [comment]
hy
I can do this can u pls assign this to me?

**Comment by Parth-2609** [comment]
Hey i have done advanced lvl of css can you assign this to me

**Comment by Hasnainqari** [comment]
Hey, Bro I'm perfect for this issue so you can assign to me 
Thankyou for your corpration

**Comment by Shreyaww** [comment]
Hi Sir, I've recently done some animation related stuff. I've brushed up my knowledge. Can you please assign this to me?
