### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by geetanjaliverma** [NiallEccles/Hacktoberfest-animations#527]
I would like to add favicon to the title .Please assign me this issue.

**Comment by sneha-mariam** [comment]
hy,
I can add favicon can u pls assign me?

**Comment by bristi07** [comment]
Hello 
It's my first project .I would like to add favicon can you pls assign it to me

**Comment by Hasnainqari** [comment]
can you assign me 
you can 
so please assign me for this issue.
