### ISSUE TITLE
Add sliding color animation

### ISSUE THREAD

**Issue by nikhilkalburgi** [NiallEccles/Hacktoberfest-animations#616]
PR #608 solves this.

**Comment by insanemindsk** [comment]
is it hacktoberfest accepted? i want to work on this please assign it to me

**Comment by NiallEccles** [comment]
Yes it is accepted. You can add your animation by following the readme :)

**Comment by insanemindsk** [comment]
Please asssign me this

**Comment by NiallEccles** [comment]
I don't need to assign the issue to you. It's an old issue, but you can add your own animation by following the readme instructions :)
