### ISSUE TITLE
add shake animation

### ISSUE THREAD

**Issue by PragyaDehal12** [NiallEccles/Hacktoberfest-animations#620]

**Comment by ZainabR11** [comment]
Hi Team, I'm eager to take on this exciting challenge!

**Comment by ZainabR11** [comment]
I can add shake animation. @NiallEccles

**Comment by insanemindsk** [comment]
is it hacktoberfest accepted? i want to work on this please assign it to me

**Comment by NiallEccles** [comment]
Yes it is accepted. You can add your animation by following the readme :)

**Comment by insanemindsk** [comment]
then please assign it to me

**Comment by NiallEccles** [comment]
I don't need to assign the issue to you. It's an old issue, but you can add your own animation by following the readme instructions :)

**Comment by insanemindsk** [comment]
if this is an old issue

> I don't need to assign the issue to you. It's an old issue, but you can add your own animation by following the readme instructions :)

if this is an old issue will it be beneficial for hacktoberfest 2023

**Comment by NiallEccles** [comment]
It's not even really an issue. Sometimes people create an issue to add an animation when it's unnecessary. There are already 15 shake animations

**Comment by insanemindsk** [comment]
> It's not even really an issue. Sometimes people create an issue to add an animation when it's unnecessary. There are already 15 shake animations

okay i got it but i want to work on issues for hacktoberfest
