### ISSUE TITLE
Hacktoberfest 2023

### ISSUE THREAD

**Issue by NiallEccles** [NiallEccles/Hacktoberfest-animations#639]
- Fork this repo
- Create a new CSS file with your cool animation name inside `./animations` folder, be creative!
- Edit the `./animations.js` file to include your animation using the following structure:

```js
{
    name: 'the-name-of-your-animation',
    author: 'your-github-username'
}
```

<sub>**PS**: the animation name should have the same name of your CSS file.</sub><br>
<sub>**PS²**: although it is not necessary to include your object alphabetically (there is a function that will do this automatically afterwards), it is recommended that you do so to keep the project organized.</sub><br>
<sub>**PS³**: use the same name of your CSS file as your animation class. Example: a file named `my-cool-animation.css` containing a `.my-cool-animation` class inside.</sub>

- Submit a merge request

- DONE!

You don't need to be assigned to this issue to participate.

If you have any problems/questions or issues please submit an issue and I will get to you!

Don't forget to star!

**Comment by shivankurchavan** [comment]
id like to work on this issue

**Comment by NiallEccles** [comment]
You can contribute without being assigned to this issue :)

**Comment by shivankurchavan** [comment]
okay, thank you!

**Comment by shivankurchavan** [comment]
> You can contribute without being assigned to this issue :)

Done ✅

**Comment by Navise** [comment]
Hey 👍 , i have created a pull request :)

**Comment by Captainnik53** [comment]
> Hey 👍 , i have created a pull request :)

I think something is wrong with your pull request, it gets displayed here otherwise 🤔

**Comment by anshul-132002** [comment]
hey ! I like to work on this issue

**Comment by kapiljain15778** [comment]
hii pls assign this task to me

**Comment by NiallEccles** [comment]
# Anyone can contribute to this repo :) You do not need to be assigned this issue. This issue is for visibility. 

## How to contribute

- Fork this repo
- Create a new CSS file with your cool animation name inside `./animations` folder, be creative!
- Edit the `./animations.js` file to include your animation using the following structure:

```js
{
    name: 'the-name-of-your-animation',
    author: 'your-github-username'
}
```

<sub>**PS**: the animation name should have the same name of your CSS file.</sub><br>
<sub>**PS²**: although it is not necessary to include your object alphabetically (there is a function that will do this automatically afterwards), it is recommended that you do so to keep the project organized.</sub><br>
<sub>**PS³**: use the same name of your CSS file as your animation class. Example: a file named `my-cool-animation.css` containing a `.my-cool-animation` class inside.</sub>

- DONE!

**Comment by 0nikhilkumar** [comment]
Sir I am hacktoberfest'23 participants so please merge this Pull Request and give the label of "hacktoberfest-accepted" then its counted for merging 1PR in hacktoberfest'23 event. @NiallEccles 

Thank you sir.

**Comment by ZainabR11** [comment]
Can I also contribute to this issue for hacktoberfest 2023. I would love to add creativity in this. Is this repo hacktoberfest accepted? @NiallEccles

**Comment by NiallEccles** [comment]
## How to contribute

- Fork this repo
- Create a new CSS file with your cool animation name inside `./animations` folder, be creative!
- Edit the `./animations.js` file to include your animation using the following structure:

```js
{
    name: 'the-name-of-your-animation',
    author: 'your-github-username'
}
```

<sub>**PS**: the animation name should have the same name of your CSS file.</sub><br>
<sub>**PS²**: although it is not necessary to include your object alphabetically (there is a function that will do this automatically afterwards), it is recommended that you do so to keep the project organized.</sub><br>
<sub>**PS³**: use the same name of your CSS file as your animation class. Example: a file named `my-cool-animation.css` containing a `.my-cool-animation` class inside.</sub>

- DONE!

**Comment by ZainabR11** [comment]
Is this repo hacktoberfest accepted?
