### ISSUE TITLE
Create your own hacktoberfest animation

### ISSUE THREAD

**Issue by NiallEccles** [NiallEccles/Hacktoberfest-animations#9]
- Fork this repo
- Create a new CSS file with your cool animation name inside `./animations` folder, be creative!
- Edit the `./animations.js` file to include your animation using the following structure:

```js
{
    name: 'the-name-of-your-animation',
    author: 'your-github-username'
}
```

<sub>**PS**: the animation name should have the same name of your CSS file.</sub><br>
<sub>**PS²**: although it is not necessary to include your object alphabetically (there is a function that will do this automatically afterwards), it is recommended that you do so to keep the project organized.</sub><br>
<sub>**PS³**: use the same name of your CSS file as your animation class. Example: a file named `my-cool-animation.css` containing a `.my-cool-animation` class inside.</sub>

- Submit a merge request

- DONE!

If you have any problems/questions or issues please submit an issue and I will get to you!

Don't forget to star!

**Comment by lozinska** [comment]
Hello there! I would also like to add hacktoberfest animation as my first PR. I will work on it today and send request later today. Thank you.

**Comment by wajeehsheikh** [comment]
Hi 
I would like to add an animation to this project.
Thanks,
Waj

**Comment by hidalgo-vntu** [comment]
Hi
I would like to add an animation to this project.
Thanks

**Comment by Rainbow-Ninja** [comment]
is this open for hacktoberfest this year?

**Comment by devarshidoshi** [comment]
Added Water Wave Effect Its My First PR if you love it please approve it

**Comment by NiallEccles** [comment]
> is this open for hacktoberfest this year?

Sure is!

**Comment by kalpanaT-05** [comment]
hey @NiallEccles can i contribute on this project, since i've found this project very interesting, therefore i'd like to give it a go

**Comment by NiallEccles** [comment]
@kalpanaT-05 you sure can! There is a README.md file that should walk you through the steps for adding your own animation!

**Comment by kalpanaT-05** [comment]
> @kalpanaT-05 you sure can! There is a README.md file that should walk you through the steps for adding your own animation!

thank you so much just assign me this project so that i can fork and start working

**Comment by kalpanaT-05** [comment]
@NiallEccles i've created a PR please check it and make sure to merge it

**Comment by ainneo** [comment]
I would like to be added - I have already submitted 3 PRs and want to make this project my 4th. May I be added? Thank you.

**Comment by mamadou-diallo** [comment]
I'd like to contribute to this :) !

**Comment by sniemeyer1** [comment]
I'd like to contribute an animation please!

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by NiallEccles** [comment]
sure can @srishtij2000 !

**Comment by harjotkarwal** [comment]
#363

**Comment by shriyag35** [comment]
@NiallEccles I have created a pull request. If you can please merge it, that would be great! If there are any issues, I would love to fix them. I have already fixed the issues you previously assigned.

**Comment by himanshubobade** [comment]
can i contribute?? @NiallEccles

**Comment by NiallEccles** [comment]
@himanshubobade sure can!

**Comment by seanevans-test** [comment]
@NiallEccles Hi, I have created a pull request with my animation, are you able to merge it, many thanks.

**Comment by pushpanjali-10** [comment]
Hi
I would like to add an animation to this project.
Thanks

**Comment by NiallEccles** [comment]
> Hi I would like to add an animation to this project. Thanks

Sure thing! Follow the instructions in the readme!

**Comment by NiallEccles** [comment]
> Hi!! I'd like to contribute an animation please! I'll try to make the best animation. Pls assign me this issue. Thanks

@nancy0119 You can contribute to this! Just follow the instructions in the readme :)

**Comment by Hasindu5512** [comment]
Hi!!, I would like to add animation, Can you please assign me for this?

**Comment by AnshuPathak-88825** [comment]
@NiallEccles pls assign me this issue

**Comment by ArihantJain123** [comment]
I would to work on this issue can you assign me under hecktoberfest ? thank you

**Comment by NiallEccles** [comment]
@Hasindu5512 @AnshuPathak-88825 @ArihantJain123 
You can fork this repo and then make your PR! I don't need to assign this to you :)

**Comment by AnshuPathak-88825** [comment]
@NiallEccles  I have created pull request pls merge

**Comment by AnshuPathak-88825** [comment]
@NiallEccles pls merge my pull request

**Comment by TheShubham-K** [comment]
Hi
I would like to add an animation to this project.
Thanks

**Comment by suyesha07** [comment]
I would like to work on it. Please assign me this. sir

**Comment by sajdakabir** [comment]
Hey NiallEccles, I would like to add animation, Can you please assign me for this?

**Comment by 123shuklaayush** [comment]
would like to add css 3d text. May I?

**Comment by Akash-1gif** [comment]
> Hey I'm interested to contribute my animation to this project

**Comment by 123shuklaayush** [comment]
Hello sir, I've added two more effects. Please see them and if they face any issue please tell me, I will resolve that

**Comment by Yash-RajSingh** [comment]
Hey @NiallEccles, I'd like to contribute to this issue and add my own animation but I had a doubt, Are we allowed to add our own font file and image if they are involved in the animation?

**Comment by tarunmankar** [comment]
Added my text animation #542

**Comment by ZeelParekh10** [comment]
Hello sir, found this repo interesting, can I contribute in it under hacktoberfest ??

**Comment by brumcaroline** [comment]
Hi, 
I would like to add an animation to this project too :)

**Comment by stevenanthonyrevo** [comment]
I went ahead and added animation #575

**Comment by rodrigoodev** [comment]
i'm working in this issue in this PR #585

**Comment by yashneet-kalra** [comment]
Hi @NiallEccles , I've raised a PR #628 for this issue. Kindly review it.

**Comment by yashneet-kalra** [comment]
Hi @NiallEccles , I've raised a PR #632 regarding this issue. Kindly review it.
Thank you

**Comment by yashneet-kalra** [comment]
Hi @NiallEccles , can you please take a look at my PR #632 and merge it as it is the last day of Hacktoberfest! 
Thank you!

**Comment by anshul-132002** [comment]
hey ! @NiallEccles i want to contribute to this issue

**Comment by sharsha315** [comment]
Hi @NiallEccles , I would like to contribute to this issue by adding animation.

**Comment by 0nikhilkumar** [comment]
Sir I am hacktoberfest'23 participants so please merge this Pull Request and give the label of "hacktoberfest-accepted" then its counted for merging 1PR in hacktoberfest'23 event. @NiallEccles 

Thank you sir.
